import type { Metadata } from "next";

import "./globals.css";
import Wrapper from "@/components/wrapper";
import { AppProvider } from "./context";

export const metadata: Metadata = {
  title: "Keyboard master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AppProvider>
      <Wrapper>{children}</Wrapper>
    </AppProvider>
  );
}
