import type { Metadata } from "next";

import "./globals.css";
import Wrapper from "components/wrapper";



export const metadata: Metadata = {
  title: "Keyboard master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
   <Wrapper>{children}</Wrapper>
  );
}
